don't run pr checker when gh pr create fails

diff --git a/home/.local/bin/ghpr b/home/.local/bin/ghpr
--- a/home/.local/bin/ghpr
+++ b/home/.local/bin/ghpr
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 gh pr create
+exit_code=$?
 
-echo "Firing up the PR checker in the background..."
-~/.local/bin/prchecker.py &
+if [ $exit_code -eq 0 ]; then
+    echo "Firing up the PR checker in the background..."
+    ~/.local/bin/prchecker.py &
+else
+    echo "Not running prchecker, pr create failed with exit code $exit_code"
+fi
